# Generated by Django 2.2.16 on 2023-01-06 22:39

from django.db import migrations, models
import django.db.models.deletion
import functools
import project.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_start', models.DateTimeField(blank=True, null=True)),
                ('contract_end', models.DateTimeField(blank=True, null=True)),
                ('rent_amount_per_month', models.IntegerField(blank=True, null=True)),
                ('contract_photo', models.ImageField(blank=True, null=True, upload_to=functools.partial(project.helpers.file_upload, *('contract_photo',), **{}))),
                ('renter_id_photo', models.ImageField(blank=True, null=True, upload_to=functools.partial(project.helpers.file_upload, *('renter_id_photo',), **{}))),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_property', to='project.Properties')),
            ],
        ),
    ]
