# Generated by Django 2.2.16 on 2023-01-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230106_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='first_paragraph_text_ar',
            field=models.TextField(default='', help_text='description of first paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='first_paragraph_text_en',
            field=models.TextField(default='', help_text='description of first paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='first_paragraph_title_ar',
            field=models.CharField(default='', help_text='title of first paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='first_paragraph_title_en',
            field=models.CharField(default='', help_text='title of first paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='forth_paragraph_text_ar',
            field=models.TextField(default='', help_text='description of forth paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='forth_paragraph_text_en',
            field=models.TextField(default='', help_text='description of forth paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='forth_paragraph_title_ar',
            field=models.CharField(default='', help_text='title of forth paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='forth_paragraph_title_en',
            field=models.CharField(default='', help_text='title of forth paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='second_paragraph_text_ar',
            field=models.TextField(default='', help_text='description of second paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='second_paragraph_text_en',
            field=models.TextField(default='', help_text='description of second paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='second_paragraph_title_ar',
            field=models.CharField(default='', help_text='title of second paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='second_paragraph_title_en',
            field=models.CharField(default='', help_text='title of second paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='third_paragraph_text_ar',
            field=models.TextField(default='', help_text='description of third paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='third_paragraph_text_en',
            field=models.TextField(default='', help_text='description of third paragraph in about us page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='third_paragraph_title_ar',
            field=models.CharField(default='', help_text='title of third paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='third_paragraph_title_en',
            field=models.CharField(default='', help_text='title of third paragraph in about us page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='address_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='description of property', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='description of property', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
